# Generated by Django 2.0 on 2020-11-03 07:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AddField(
            model_name='picture',
            name='extension',
            field=models.CharField(db_index=True, default=1, max_length=5, verbose_name='Расширение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picture',
            name='height',
            field=models.IntegerField(db_index=True, default=1, verbose_name='Высота изображения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picture',
            name='thumbnail',
            field=models.ImageField(default=1, upload_to='images', verbose_name='Миниатюра изображения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picture',
            name='uploaded_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата и время загрузки'),
        ),
        migrations.AddField(
            model_name='picture',
            name='width',
            field=models.IntegerField(db_index=True, default=1, verbose_name='Ширина изображения'),
            preserve_default=False,
        ),
    ]
